### ISSUE TITLE
Problem on 4 inch phones MDPI

### ISSUE THREAD

**Issue by GadgetCheck** [rahulrj/YahooNewsOnboarding#1]
Sunmoonview is not in the center and gets aligned to the right and basically gets distorted.

**Comment by rahulrj** [comment]
@GadgetCheck , Will look into it. As it was just a demo, i hardcoded the dp values into the app. So this problem might arise. Will fix this.

**Comment by GadgetCheck** [comment]
Rahul, i was trying to fix it but no luck (wanted to apply this to my app today :D). would be great if you could fix it. 

I am not able to draw it in the centre.

Waiting for your patch.

Its happening on the second and third layouts that is sunmoonview and thirdscreen view.

**Comment by rahulrj** [comment]
Okay. I will fix this by today or most  probably by tomorrow. For center horizontal, i guess i will have to pass x-co-ordinate as deviceWidth/2.

**Comment by GadgetCheck** [comment]
Yeah, like i tried it on an oneplus 2 and all the 3 screens went out of proportion, even on a note 5 same thing happened. I am guessing you need to make it automatically scale up/down.

Like the yahoo app scaled like a charm.

**Comment by rahulrj** [comment]
@GadgetCheck  can you please send me a screenshot of the distorted screen on my mail rahul.110392@gmail.com or you can attach here also?

**Comment by serkandyck** [comment]
hey rahul here screen nexus 5 first steep fine
http://i57.tinypic.com/juzfpv.png step 2
http://i59.tinypic.com/s3opcw.png Step 3

**Comment by rahulrj** [comment]
HI.
I improved the second and third screen to a good extent by dynamically sizing the contents. It should work for now.But its not a full proof solution. Give me time upto Monday. I will make all the three screens  resizable across most of the devices.

**Comment by GadgetCheck** [comment]
Done bro, awesome job. Waiting for the proper fix.

**Comment by rahulrj** [comment]
@GadgetCheck @asdstyle33 I have made the fixes for dimensions and tested also in the emulators.  You can use them.

**Comment by GadgetCheck** [comment]
Perfect thanks @rahulrj
